import { useRef, useState, type FormEvent } from 'react'
import { motion, useScroll, useSpring, useTransform } from 'motion/react'
import { Activity, ArrowDown, ArrowRight, Brain, Check, HeartPulse, Home, LockKeyhole, ShieldCheck, Sparkles, Stethoscope, Utensils, Watch, X } from 'lucide-react'
import { SignupButton } from './auth'

const screens = [
  { src:'/screens/overview.svg', label:'ONE VIEW', title:'See the whole picture.', copy:'Sleep, activity, nutrition and habits come together in one calm overview instead of being scattered across different tools.', alt:'WellMate overview screen' },
  { src:'/screens/physical.svg', label:'PHYSICAL', title:'Know what your body is telling you.', copy:'Track workouts, activity, recovery and nutrition so the numbers have context — and become useful.', alt:'WellMate physical health screen' },
  { src:'/screens/nutrition.svg', label:'NUTRITION', title:'Every meal becomes context.', copy:'Log what you eat and build a picture of calories, protein, fats, carbohydrates and the patterns behind them.', alt:'WellMate nutrition screen' },
  { src:'/screens/habits.svg', label:'HABITS', title:'Make consistency visible.', copy:'Turn small actions into rhythms you can actually see, understand and continue.', alt:'WellMate habits screen' },
  { src:'/screens/mental.svg', label:'MENTAL WELLBEING', title:'A place to talk things through.', copy:'WellMate combines mood, reflection and a calm conversational space for the moments when you need support.', alt:'WellMate mental wellbeing screen' },
]
const pillars=[
  ['01 — NUTRITION','Eat with context.','Meal logging and nutrient tracking give WellMate the information it needs to understand how your intake fits into the rest of your day.'],
  ['02 — MOVEMENT','Train with purpose.','Workouts and activity become part of the same picture as recovery, habits and how you feel.'],
  ['03 — RECOVERY','Sleep is part of the plan.','Track sleep and recovery alongside the rest of your wellbeing, because a good day does not begin with a workout alone.'],
]
const wearables = [
  { name:'Apple Watch', caption:'Vitals · activity · recovery', src:'/smartwatch-apple.svg' },
  { name:'Samsung Galaxy Watch', caption:'Health signals · movement · sleep', src:'/smartwatch-samsung.svg' },
  { name:'WHOOP', caption:'Recovery · strain · sleep', src:'/smartwatch-whoop.svg' },
]

function HeroScreen({ jump, original }:{jump:(id:string)=>void, original?:boolean}){
  const hero=useRef<HTMLElement>(null)
  const {scrollYProgress}=useScroll({target:hero,offset:['start start','end start']})
  const scale=useSpring(useTransform(scrollYProgress,[0,1],[1,.9]),{stiffness:80,damping:20})
  const y=useTransform(scrollYProgress,[0,1],[0,100])
  return <section ref={hero} className="hero">
    <motion.div className="hero-copy" style={{y}}>
      <motion.p className="kicker" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.25}}>{original?'A NEW KIND OF WELLBEING COMPANION':'EMERGENCY CARE, REIMAGINED'}</motion.p>
      <motion.h1 initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{delay:.4,duration:.9}}>{original?<>Your whole<br/><em>self, understood.</em></>:<>Bridging the<br/><em>Golden Hour.</em></>}</motion.h1>
      <motion.p className="hero-lede" initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{delay:.65}}>{original?'WellMate brings nutrition, movement, sleep, habits and mental wellbeing together — then turns what you log into guidance from your personal AI companion.':'Bridging the Golden Hour gap between accident and action, SynkCare makes emergency healthcare instantly accessible to everyone, anytime and anywhere.'}</motion.p>
      <motion.div className="hero-actions" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.85}}>
        <SignupButton className="primary" onFallback={()=>jump('access')}>Get WellMate <ArrowRight size={16}/></SignupButton>
        <button className="quiet-button" onClick={()=>jump(original?'experience':'emergency-problem')}>{original?'See the product':'See why it matters'} <ArrowDown size={16}/></button>
      </motion.div>
    </motion.div>
    <motion.div className="hero-product" style={{scale}}>
      <div className="hero-glow"/>
      <div className="floating-label one">{original?<><Utensils size={14}/> NUTRITION</>:<><HeartPulse size={14}/> EMERGENCY</>}</div>
      <div className="floating-label two">{original?<><Activity size={14}/> MOVEMENT</>:<><ShieldCheck size={14}/> SAFETY</>}</div>
      <div className="floating-label three">{original?<><Brain size={14}/> MENTAL</>:<><Activity size={14}/> CONTEXT</>}</div>
      <div className="device-frame hero-device"><div className="device-notch"/><img src={screens[0].src} alt={screens[0].alt}/></div>
    </motion.div>
    <div className="hero-foot"><span>THE PERSONAL WELLBEING SYSTEM</span><span>SCROLL TO EXPLORE ↓</span></div>
  </section>
}

export default function App(){
 const [menu,setMenu]=useState(false),[active,setActive]=useState(0),[email,setEmail]=useState(''),[sent,setSent]=useState(false)
 const jump=(id:string)=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
 const submit=(e:FormEvent)=>{e.preventDefault();if(email.trim())setSent(true)}
 return <main><div className="grain" aria-hidden="true"/><header className="header"><button className="brand" onClick={()=>jump('top')}><span>W</span>WELLMATE</button><nav className={menu?'nav open':'nav'} aria-label="Primary"><button onClick={()=>jump('experience')}>Product</button><button onClick={()=>jump('intelligence')}>WellMate AI</button><button onClick={()=>jump('safety')}>Safety</button><button onClick={()=>jump('future')}>Future</button><button onClick={()=>jump('access')}>Join</button></nav><SignupButton className="nav-cta" onFallback={()=>jump('access')}>Get WellMate <ArrowRight size={15}/></SignupButton><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X size={21}/>:<span>MENU</span>}</button></header>
 <section id="top" className="golden-hero"><HeroScreen jump={jump}/></section>
 <section id="emergency-problem" className="golden-gap"><div className="section-meta">THE PROBLEM</div><div className="golden-gap-head"><div><p className="eyebrow">THE GOLDEN HOUR</p><h2>The gap between<br/><em>accident and action.</em></h2></div><p>In an emergency, the first minutes can matter. Yet critical context can be missing at exactly the moment it is needed — when a person cannot speak for themselves and responders are still trying to understand what happened.</p></div><div className="golden-gap-visual"><motion.div className="timeline-node accident" initial={{opacity:0,scale:.8}} whileInView={{opacity:1,scale:1}} viewport={{once:true}}><span className="node-number">01</span><HeartPulse size={28}/><strong>ACCIDENT</strong><small>An unexpected event changes everything.</small></motion.div><motion.div className="timeline-gap" initial={{scaleX:0}} whileInView={{scaleX:1}} viewport={{once:true}} transition={{duration:.8}}><span>THE GOLDEN HOUR GAP</span></motion.div><motion.div className="timeline-node action" initial={{opacity:0,scale:.8}} whileInView={{opacity:1,scale:1}} viewport={{once:true}}><span className="node-number">02</span><ShieldCheck size={28}/><strong>INFORMED ACTION</strong><small>Responders act faster when the context arrives with them.</small></motion.div></div><p className="golden-line">Bridging the Golden Hour gap between accident and action, SynkCare makes emergency healthcare instantly accessible to everyone, anytime and anywhere.</p></section>
 <section id="safety" className="safety section-wrap"><div className="section-meta">THE SOLUTION</div><div className="safety-head"><div><p className="eyebrow">DESIGNED TO HELP WHEN YOU CANNOT</p><h2>When the unexpected happens,<br/><em>WellMate can act.</em></h2></div><div className="safety-copy"><p>Using the phone’s built-in motion sensors, WellMate can watch for patterns of abrupt movement followed by an unusually stable state. When the pattern meets the configured emergency criteria, the app can escalate by contacting the user’s emergency contacts and initiating ambulance support.</p><span className="safety-note">Designed as an emergency escalation workflow — not a substitute for emergency services or medical assessment.</span></div></div><motion.div className="safety-visual" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.8}}><div className="sensor-orbit"><div className="sensor-ring ring-a"/><div className="sensor-ring ring-b"/><div className="sensor-core"><HeartPulse size={34}/><span>MOTION WATCH</span><strong>STABLE STATE</strong></div><div className="sensor-node node-1">ACCELEROMETER</div><div className="sensor-node node-2">GYROSCOPE</div><div className="sensor-node node-3">EMERGENCY SIGNAL</div></div><div className="safety-steps"><div><b>01</b><span>Detect</span><small>Sudden movement pattern</small></div><div><b>02</b><span>Confirm</span><small>Unexpected stillness</small></div><div><b>03</b><span>Escalate</span><small>Contacts + ambulance workflow</small></div></div></motion.div></section>
 <section className="critical-context"><div className="section-meta">EMERGENCY CONTEXT</div><div className="critical-grid"><div><p className="eyebrow">WHAT RESPONDERS ALREADY KNOW</p><h2>When help arrives,<br/><em>the context arrives first.</em></h2><p>During onboarding, WellMate captures critical information such as blood group, allergies and other important emergency details. When an emergency workflow is activated, that information can be shared with the responding paramedical team so they arrive with more context — including what to avoid.</p></div><motion.div className="medical-card" initial={{opacity:0,x:40}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.8}}><div className="medical-header"><span>EMERGENCY PROFILE</span><span className="status-dot">LIVE</span></div><div className="blood-type"><span>BLOOD GROUP</span><strong>B+</strong></div><div className="medical-row"><span>ALLERGIES</span><strong>Penicillin</strong></div><div className="medical-row"><span>EMERGENCY CONTACT</span><strong>Primary contact</strong></div><div className="medical-row"><span>PARAMEDIC NOTE</span><strong>Shared on escalation</strong></div><div className="medical-footer"><ShieldCheck size={15}/><span>Critical context travels with the alert.</span></div></motion.div></div></section>
 <section className="golden-breath"><div className="golden-breath-copy"><p className="eyebrow">ONE MORE THING</p><h2>WELLMATE IS ALL THAT<br/><em>AND SO MUCH MORE....</em></h2><p>From emergency response to everyday wellbeing, the same system keeps building a richer picture of you — and gives that context back in ways that are useful.</p></div></section>
 <HeroScreen jump={jump} original/>
 <section id="experience" className="manifesto section-wrap"><div className="section-meta">THE PRODUCT</div><div className="manifesto-content"><p className="display-copy">Wellness is connected. Your tools should be too.</p><p className="body-copy">A meal can affect energy. Sleep can affect mood. Habits can affect consistency. WellMate is built around those connections so your health data stops being a collection of isolated numbers.</p></div></section>
 <section className="screen-story" aria-label="Inside WellMate"><div className="screen-stage"><div className="screen-stage-copy"><p className="section-meta">INSIDE WELLMATE</p><h2>{screens[active].title}</h2><p>{screens[active].copy}</p><div className="screen-tabs" role="tablist">{screens.map((s,i)=><button key={s.label} className={i===active?'screen-tab active':'screen-tab'} onClick={()=>setActive(i)} role="tab" aria-selected={i===active}><span>{String(i+1).padStart(2,'0')}</span>{s.label}</button>)}</div></div><motion.div className="device-frame story-device" key={screens[active].src} initial={{opacity:0,y:28,scale:.97}} animate={{opacity:1,y:0,scale:1}} transition={{duration:.6,ease:[.16,1,.3,1]}}><div className="device-notch"/><img src={screens[active].src} alt={screens[active].alt}/></motion.div></div></section>
 <section className="disciplines">{pillars.map(([ey,title,copy],i)=><motion.article className="discipline" key={ey} initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-12% 0px'}} transition={{duration:.75,delay:i*.08}}><div className="discipline-index">{ey}</div><h2>{title}</h2><p>{copy}</p><div className="discipline-line"/></motion.article>)}</section>
 <section id="intelligence" className="intelligence section-wrap"><div className="section-meta">THE INTELLIGENCE LAYER</div><div className="intelligence-stage"><div className="intel-copy"><p className="eyebrow">MEET WELLMATE</p><h2>Your personal<br/><em>wellbeing team.</em></h2><p>WellMate is designed to feel less like a chatbot and more like a companion: a personal trainer for your activity, a nutrition guide for your meals, and a mental wellbeing advisor when life gets heavy.</p><div className="signal-list">{['Personal trainer','Nutrition companion','Mental wellbeing advisor'].map(x=><div className="signal" key={x}><Check size={14}/>{x}</div>)}</div></div><motion.div className="intel-panel" initial={{opacity:0,x:50}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.9}}><div className="panel-header"><span>WELLMATE / PERSONAL AI</span><span>LIVE CONTEXT</span></div><div className="panel-title">Your data becomes<br/><em>conversation.</em></div><div className="context-orbit"><span className="context-node node-a">MEALS</span><span className="context-node node-b">SLEEP</span><span className="context-node node-c">ACTIVITY</span><span className="context-node node-d">MOOD</span><div className="context-core">W</div></div><div className="panel-insight"><span className="insight-dot"/>WellMate combines what you track to give advice grounded in your actual routine, not a generic wellness checklist.</div><div className="panel-footer"><span>PERSONAL CONTEXT</span><ArrowRight size={14}/></div></motion.div></div></section>
 <section className="ai-chat section-wrap"><div className="section-meta">HOW WELLMATE HELPS</div><div className="chat-layout"><div className="chat-copy"><p className="eyebrow">ASK WELLMATE ANYTHING</p><h2>From “what should I eat?” to “I had a hard day.”</h2><p>WellMate is there for practical questions and human ones — using your personal context to make the answer more relevant.</p></div><div className="chat-window"><div className="chat-head"><div><strong>WellMate</strong><span>Your personal wellbeing companion</span></div><span className="online-dot">●</span></div><div className="chat-bubble user-bubble">I slept badly and I’m feeling drained today. Should I still work out?</div><div className="chat-bubble ai-bubble">Let’s look at the whole picture. Your sleep was shorter than usual, and you’ve already logged a meal. A lighter session may make more sense today. Want me to suggest one?</div><div className="chat-options"><button>Suggest a workout <ArrowRight size={14}/></button><button>Tell me what to eat <ArrowRight size={14}/></button></div></div></div></section>
 <section className="approach section-wrap"><div className="section-meta">THE APPROACH</div><div className="approach-content"><h2>Data in.<br/><em>Context out.</em></h2><div className="approach-copy"><p>Our proprietary wellbeing context layer connects what you log across meals, sleep, movement, habits and mood so WellMate can reason from your personal pattern instead of isolated snapshots.</p><div className="flow"><div><b>01</b><span>Log</span><small>Meals · sleep · movement · mood · habits</small></div><ArrowRight/><div><b>02</b><span>Connect</span><small>Your inputs become personal context</small></div><ArrowRight/><div><b>03</b><span>Guide</span><small>WellMate turns context into practical guidance</small></div></div></div></div></section>
 <section id="future" className="future section-wrap"><div className="section-meta">COMING NEXT</div><div className="future-hero"><div><p className="eyebrow">THE NEXT LAYER OF WELLMATE</p><h2>More care.<br/><em>More quietly.</em></h2></div><p>WellMate is being shaped into a broader care ecosystem: private access to professionals from home, and a connected layer of wearable data that can make the rest of the product smarter without asking users to do more.</p></div><div className="consultation"><div className="future-label"><span>01 — PROFESSIONAL CARE</span><LockKeyhole size={17}/></div><div className="consult-grid"><div><h3>Talk to a doctor, therapist or nutritionist — from home.</h3><p>Voice and video consultations designed around the comfort of home. Especially for therapy, privacy is not an afterthought: the experience is built to make it easier to speak openly in a private environment.</p><div className="care-points"><span><Home size={15}/> From the comfort of home</span><span><LockKeyhole size={15}/> Privacy-first experience</span><span><Stethoscope size={15}/> Doctors · therapists · nutritionists</span></div></div><div className="consult-card"><div className="consult-avatar"><Sparkles size={24}/></div><div className="consult-title">PRIVATE CONSULTATION</div><div className="consult-line"/><div className="consult-people"><span>Doctor</span><span>Therapist</span><span>Nutritionist</span></div><div className="consult-footer"><span>VOICE + VIDEO</span><ShieldCheck size={16}/></div></div></div></div><div className="wearable-section"><div className="future-label"><span>02 — WEARABLE INTEGRATION</span><Watch size={17}/></div><div className="wearable-head"><h3>Your vitals, without the extra effort.</h3><p>WellMate is exploring partnerships with leading wearable platforms so heart rate, sleep, activity and recovery signals can flow directly into the experience.</p></div><div className="watch-rail">{wearables.map((wearable,i)=><motion.article key={wearable.name} className="watch-card" initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.7,delay:i*.12}}><div className="watch-image"><img src={wearable.src} alt={`${wearable.name} wearable concept`}/><span className="watch-badge">EXPLORING</span></div><div className="watch-info"><h4>{wearable.name}</h4><p>{wearable.caption}</p></div></motion.article>)}</div><div className="integration-line"><div><Activity size={17}/><span>Workout intelligence</span></div><ArrowRight/><div><HeartPulse size={17}/><span>Vital context</span></div><ArrowRight/><div><Check size={17}/><span>Smarter recommendations</span></div><ArrowRight/><div><Watch size={17}/><span>Less manual logging</span></div></div></div></section>
 <section className="ai-claim section-wrap"><div className="big-quote">The future of wellbeing<br/>should feel <em>effortless.</em></div><p>More context for WellMate. Less work for you.</p></section>
 <section id="access" className="access section-wrap"><div className="access-panel"><div><p className="eyebrow">JOIN WELLMATE</p><h2>Make your wellbeing<br/><em>one conversation.</em></h2></div><div className="access-actions"><SignupButton className="account-button" onFallback={()=>document.getElementById('email')?.focus()}>Create your account <ArrowRight size={16}/></SignupButton><div className="or-rule"><span>or leave your email</span></div>{sent?<div className="success-state"><Check size={18}/><strong>You are on the list.</strong><span>We’ll see you inside.</span></div>:<form className="access-form" onSubmit={submit}><label htmlFor="email">Your email</label><div className="form-row"><input id="email" name="email" type="email" autoComplete="email" required placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><button type="submit">Request access <ArrowRight size={16}/></button></div><p>A simple way to be first in when WellMate is ready.</p></form>}</div></div></section>
 <footer className="footer section-wrap"><div className="footer-brand"><span className="wordmark-mark">W</span><span>WELLMATE</span></div><p>Built around the whole person.</p><button onClick={()=>jump('top')}>Back to top <ArrowRight size={15}/></button></footer></main>
}
